version: '3.8'

services:
  app:
    build: .
    container_name: java_eye_api
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=development
    restart: unless-stopped

