version: '3.8'

services:
  app:
    build: .
    container_name: java_eye_api
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - deploy_net


networks:
  deploy_net:
    external: true


