name: Deploy to VPS without GitHub Deploy Key

on:
  push:
    branches:
      - deployment_test

jobs:
  deploy:
    name: Build and Deploy App to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/custom_rsa
          chmod 600 ~/.ssh/custom_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # - name: Sync project files to VPS
      #   run: |
      #     rsync -avz -e "ssh -i ~/.ssh/custom_rsa" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/app

      - name: SSH into VPS and deploy
        run: |
          ssh -i ~/.ssh/custom_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/app
            docker-compose down
            docker-compose up -d --build
          EOF
